```{r}
X <- {}
n <- 1000
p <- 10000
for(i in seq_along(n)) { 
  x <- rsign(p) 
  X <- rbind(X,x)
  beta <- rep(1, p) \
  epsilon <- rnorm(n)
  y <- X %*% beta + epsilon

}


beta <- rep(1, p)
epsilon <- rnorm(n)
y <- X %*% beta + epsilon

datasetB <- data.frame("y" = y, "x" = X)
train_ind <- sample(1:nrow(datasetB), 0.5 * nrow(datasetB))
x.train <- X[train_ind, ] 
x.test <- X[-train_ind, ] 
y.train <- y[train_ind] 
y.test <- y[-train_ind]


lambda_grid <- c(0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10, 20, 50, 100)
train_MSE <- rep(0, length(lambda_grid)) 
best_train_lambda <- rep(0, num_folds) 
best_lambda <- rep(0, num_folds)
test_MSE <- rep(0, length(lambda_grid)) 
best_test_lambda <- rep(0, num_folds) 
minMSE.test <- rep(0, num_folds)
risk <- rep(0, length(lambda_grid)) 
best_lambda_risk <- rep(0, num_folds) 
min_MSE_risk <- rep(0, num_folds)
train_MSE_arr <- {}
test_error_df <- {}
risk_df <- {}


num_folds <- num_folds 
n <- 500
for (fold in seq_along(num_folds)){
  valid <- ((k-1)*(n/num_folds) + 1):(fold*(n/num_folds)) 
  X_train <- x.train[-valid, ]
  Y_train <- y.train[-valid]
  X.valid <- x.train[valid, ]
  Y.valid <- y.train[valid]
  for (i in seq_along(length(lambda_grid)){
    risk_beta <- glmnet(X.valid, Y.valid, alpha = 0, lambda = lambda_grid[i])["beta"]
    train_MSE[i] <- mean((Y.valid - X.valid %*% risk_beta[[1]])^2) 
    test_MSE[i] <- mean((x.test %*% risk_beta[[1]] - y.test)^2)
    risk[i] <- 1 + t(risk_beta[[1]] - beta) %*% (risk_beta[[1]] - beta) 
  }
  train_MSE_arr <- rbind(train_MSE_arr, train_MSE) 
  test_error_df <- rbind(test_error_df, test_MSE)
  risk_df <- rbind(risk_df, risk)
  best_train_lambda[fold] = lambda_grid[which.min(train_MSE)]
  best_lambda[fold] = min(train_MSE)
  best_test_lambda[fold] = lambda_grid[which.min(test_MSE)] 
  minMSE.test[fold] = min(test_MSE)
  best_lambda_risk[fold] = lambda_grid[which.min(risk)]
  min_MSE_risk[fold] = min(risk) 
}
